import os
import shutil
import glob
from datetime import datetime

# Configuration
DIST_DIR = "dist"
WAREHOUSE_DIR = "final_video_warehouse"
TITLE = "Aegis Manim Gallery"

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {{
            theme: {{
                extend: {{
                    colors: {{
                        paper: '#fffdf5',
                        ink: '#2d2d2d',
                        brand: {{ DEFAULT: '#6366f1', 50: '#eef2ff', 100: '#e0e7ff', 600: '#4f46e5', 700: '#4338ca' }}
                    }}
                }}
            }}
        }}
    </script>
    <style>
        .aegis-app {{
            background-color: #fffdf5;
            font-family: system-ui, -apple-system, sans-serif;
        }}
        .aegis-sketchy-border {{
            border: 2px solid #2d2d2d;
            border-radius: 2px 255px 3px 25px / 255px 5px 225px 3px;
        }}
        .aegis-card-sketchy {{
            border: 2px solid #2d2d2d;
            border-radius: 5px;
            box-shadow: 4px 4px 0px rgba(0, 0, 0, 0.15);
            transition: all 0.2s;
            background: white;
            overflow: hidden;
        }}
        .aegis-card-sketchy:hover {{
            transform: rotate(-1deg) scale(1.02);
            box-shadow: 6px 6px 0px #4f46e5;
            z-index: 10;
        }}
        .aegis-btn-sketchy {{
            border: 2px solid #2d2d2d;
            border-radius: 255px 15px 225px 15px / 15px 225px 15px 255px;
            box-shadow: 2px 3px 0px rgba(0, 0, 0, 0.8);
            transition: all 0.1s ease-in-out;
            background: white;
            font-weight: 700;
        }}
        .aegis-btn-sketchy:hover {{
            box-shadow: 1px 1px 0px rgba(0, 0, 0, 0.8);
            transform: translate(1px, 2px);
        }}
    </style>
</head>
<body class="bg-slate-100 min-h-screen py-8 px-4">
    <div class="aegis-app w-full max-w-6xl mx-auto aegis-sketchy-border p-1 min-h-[800px] text-ink shadow-[5px_5px_0px_rgba(0,0,0,0.2)] flex flex-col">
        
        <!-- Header -->
        <div class="px-6 py-6 border-b-2 border-dashed border-slate-300 bg-paper relative overflow-hidden text-center md:text-left">
            <div class="relative z-10">
                <div class="flex flex-col md:flex-row items-center gap-3 mb-2 justify-center md:justify-start">
                    <span class="text-xs font-black bg-brand-600 text-white px-2 py-0.5 transform -rotate-2">MANIM POWERED</span>
                    <h1 class="text-3xl font-black text-ink">{title}</h1>
                </div>
                <p class="text-slate-600 font-medium">
                    Aegis 动态经济学图表库 · <strong class="text-brand-600 bg-brand-50 px-1">可视化思维</strong>
                </p>
            </div>
        </div>

        <!-- Gallery Grid -->
        <div class="flex-1 bg-slate-50/50 p-6">
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                {cards}
            </div>
        </div>
        
        <!-- Footer -->
        <div class="px-6 py-4 border-t-2 border-dashed border-slate-300 text-center text-xs text-slate-400 bg-paper">
             <p>Generated by Aegis Engine at {time} · <a href="https://github.com/yishu-ziyu/Aegis-Manim" class="hover:text-brand-600 underline">Get the Source Code</a></p>
        </div>
    </div>
</body>
</html>
"""

CARD_TEMPLATE = """
<div class="aegis-card-sketchy flex flex-col h-full">
    <div class="relative bg-black aspect-video border-b-2 border-ink">
        <video controls preload="metadata" class="w-full h-full object-contain">
            <source src="videos/{filename}" type="video/mp4">
            Your browser does not support video playback.
        </video>
    </div>
    <div class="p-4 flex flex-col flex-1 bg-white">
        <h3 class="font-black text-lg text-ink mb-1 leading-tight">{clean_name}</h3>
        <div class="flex justify-between items-center mt-auto pt-3 border-t border-slate-100">
            <span class="text-xs font-bold text-slate-400 uppercase tracking-wider">MP4 Video</span>
            <span class="text-xs font-bold bg-slate-100 text-slate-500 px-2 py-1 rounded-full">{size} MB</span>
        </div>
    </div>
</div>
"""

def get_file_size(path):
    size_mb = os.path.getsize(path) / (1024 * 1024)
    return f"{size_mb:.1f}"

def build():
    # 1. Clean and Create Dist
    if os.path.exists(DIST_DIR):
        shutil.rmtree(DIST_DIR)
    os.makedirs(os.path.join(DIST_DIR, "videos"))
    
    # 2. Scan Warehouse
    if not os.path.exists(WAREHOUSE_DIR):
        print(f"Warning: Warehouse directory '{WAREHOUSE_DIR}' not found.")
        videos = []
    else:
        videos = glob.glob(os.path.join(WAREHOUSE_DIR, "*.mp4"))
        videos.sort()

    # 3. Process Videos
    cards_html = ""
    print(f"Found {len(videos)} videos.")
    
    for video_path in videos:
        filename = os.path.basename(video_path)
        dest_path = os.path.join(DIST_DIR, "videos", filename)
        
        # Copy file
        shutil.copy2(video_path, dest_path)
        print(f"Copied: {filename}")
        
        # Generate Card
        clean_name = os.path.splitext(filename)[0].replace("_", " ")
        size = get_file_size(video_path)
        
        cards_html += CARD_TEMPLATE.format(
            filename=filename,
            clean_name=clean_name,
            size=size
        )

    # 4. Write HTML
    final_html = HTML_TEMPLATE.format(
        title=TITLE,
        cards=cards_html,
        time=datetime.now().strftime("%Y-%m-%d %H:%M")
    )
    
    with open(os.path.join(DIST_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(final_html)
    
    print(f"Build complete! Static site generated in '{DIST_DIR}/'")

if __name__ == "__main__":
    build()
