import os
import shutil
import glob
from datetime import datetime

# Configuration
DIST_DIR = "dist"
WAREHOUSE_DIR = "final_video_warehouse"
TITLE = "Aegis Manim Gallery"

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; background: #0f172a; color: #f8fafc; margin: 0; padding: 20px; }}
        header {{ text-align: center; margin-bottom: 40px; padding: 20px 0; border-bottom: 1px solid #334155; }}
        h1 {{ margin: 0; font-size: 2.5rem; background: linear-gradient(to right, #60a5fa, #34d399); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }}
        p {{ color: #94a3b8; }}
        .grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(320px, 1fr)); gap: 24px; max-width: 1200px; margin: 0 auto; }}
        .card {{ background: #1e293b; border-radius: 12px; overflow: hidden; border: 1px solid #334155; transition: transform 0.2s; }}
        .card:hover {{ transform: translateY(-5px); border-color: #60a5fa; }}
        video {{ width: 100%; display: block; background: #000; }}
        .content {{ padding: 16px; }}
        .filename {{ font-weight: 600; font-size: 1.1rem; margin-bottom: 8px; color: #e2e8f0; }}
        .meta {{ font-size: 0.85rem; color: #64748b; }}
        footer {{ text-align: center; margin-top: 60px; color: #475569; font-size: 0.9rem; }}
        a {{ color: #60a5fa; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
    </style>
</head>
<body>
    <header>
        <h1>{title}</h1>
        <p>Aegis 动态经济学图表库 | Manim Generated Assets</p>
    </header>

    <div class="grid">
        {cards}
    </div>

    <footer>
        <p>Generated by Aegis Engine at {time}</p>
        <p><a href="https://github.com/yishu-ziyu/Aegis-Manim">View Source on GitHub</a></p>
    </footer>
</body>
</html>
"""

CARD_TEMPLATE = """
<div class="card">
    <video controls preload="metadata" poster="">
        <source src="videos/{filename}" type="video/mp4">
        Your browser does not support the video tag.
    </video>
    <div class="content">
        <div class="filename">{clean_name}</div>
        <div class="meta">{size} MB</div>
    </div>
</div>
"""

def get_file_size(path):
    size_mb = os.path.getsize(path) / (1024 * 1024)
    return f"{size_mb:.1f}"

def build():
    # 1. Clean and Create Dist
    if os.path.exists(DIST_DIR):
        shutil.rmtree(DIST_DIR)
    os.makedirs(os.path.join(DIST_DIR, "videos"))
    
    # 2. Scan Warehouse
    if not os.path.exists(WAREHOUSE_DIR):
        print(f"Warning: Warehouse directory '{WAREHOUSE_DIR}' not found.")
        videos = []
    else:
        videos = glob.glob(os.path.join(WAREHOUSE_DIR, "*.mp4"))
        # Sort by name
        videos.sort()

    # 3. Process Videos
    cards_html = ""
    print(f"Found {len(videos)} videos.")
    
    for video_path in videos:
        filename = os.path.basename(video_path)
        dest_path = os.path.join(DIST_DIR, "videos", filename)
        
        # Copy file
        shutil.copy2(video_path, dest_path)
        print(f"Copied: {filename}")
        
        # Generate Card
        clean_name = os.path.splitext(filename)[0].replace("_", " ")
        size = get_file_size(video_path)
        
        cards_html += CARD_TEMPLATE.format(
            filename=filename,
            clean_name=clean_name,
            size=size
        )

    # 4. Write HTML
    final_html = HTML_TEMPLATE.format(
        title=TITLE,
        cards=cards_html,
        time=datetime.now().strftime("%Y-%m-%d %H:%M")
    )
    
    with open(os.path.join(DIST_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(final_html)
    
    print(f"Build complete! Static site generated in '{DIST_DIR}/'")

if __name__ == "__main__":
    build()
